---
- name: Create Temp Dir
  file:
    path: "{{ temp_dir }}"
    state: directory

- name: Download Ambari Source
  get_url:
    url: "{{ ambari_src_url }}"
    dest: "{{ temp_dir }}"

- name: Extract Ambari
  unarchive:
    src: "{{ temp_dir }}/apache-ambari-2.7.1-src.tar.gz"
    dest: "{{ temp_dir }}"

- name: Maven config
  shell: "mvn versions:set -DnewVersion=2.7.1.0.0"
  args:
    chdir: "{{ temp_dir }}/ambari-2.7.1-src"

- name: Maven install
  shell: "mvn -B clean install rpm:rpm -DnewVersion=2.7.1.0.0 -DbuildNumber=90430db08a5f543a97d97918cf5f711f2786ad8a -DskipTests -Dpython.ver='python >= 2.6'"
  args:
    chdir: "{{ temp_dir }}/ambari-2.7.1-src"

- name: Install rpms
  yum:
    name: "{{ temp_dir }}/{{ ambari_dir_name }}/ambari-server/target/rpm/ambari-server/RPMS/noarch/ambari-server*.rpm"
    state: present

