---
- name: Copying script to tmp
  copy:
    src: ambari-setup-bot
    dest: /tmp
    owner: root
    group: root
    mode: 0700

- name: Execute setup script
  shell: /tmp/ambari-setup-bot > /tmp/ambari-setup.log

- name: Start service
  systemd:
    name: ambari-server
    state: started
    enabled: yes
