---
- name: disable csrf security
  lineinfile:
    path: /etc/ambari-server/conf/ambari.properties
    line: 'api.csrfPrevention.enabled=false'
  notify:
    - ambari_server_restart
  
- meta: flush_handlers  

- name: get blueprint
  uri:
   url: http://localhost:8080/api/v1/blueprints
   method: GET
   user: admin
   password: admin
   force_basic_auth: yes
  register: cluster

- debug:
    var: cluster

- name: POST cluster configuration
  uri:
   url: http://localhost:8080/api/v1/blueprints/multinode-hdp
   method: POST
   body: "{{ lookup('file','jsons/2nodes/cluster_configuration.json') }}"
   status_code: 201
   user: admin
   password: admin
   force_basic_auth: yes
  register: cluster-configuration

- name: POST hostmapping
  uri:
   url: http://localhost:8080/api/v1/clusters/BigDataDevOps
   method: POST
   body: "{{ lookup('file','jsons/2nodes/hostmapping.json') }}"
   status_code: 202
   user: admin
   password: admin
   force_basic_auth: yes
  register: cluster-hostmapping

- debug:
    var: cluster-hostmapping
