---
- name: get blueprint
  uri:
   url: http://localhost:8080/api/v1/blueprints
   method: GET
   user: admin
   password: admin
   force_basic_auth: yes
  register: cluster

- debug:
    var: cluster

- name: POST cluster configuration
  uri:
   url: http://localhost:8080/api/v1/blueprints/multinode-hdp
   method: post
   body: json/2nodes/cluster_configuration.json
   user: admin
   password: admin
   force_basic_auth: yes
  register: cluster-configuration

- debug:
    var: cluster-configuration

- name: POST hostmapping
  uri:
   url: http://localhost:8080/api/v1/clusters/BigDataDevOps
   method: post
   body: json/2nodes/hostmapping.json
   user: admin
   password: admin
   force_basic_auth: yes
  register: cluster-hostmapping

- debug:
    var: cluster-hostmapping


