---
- name: Allow Ambari Ports
  firewalld:
    zone: public
    port: "{{ item }}"
    state: enabled
    permanent: true
  with_items:
  - 8080/tcp
  - 8440/tcp
  - 8441/tcp
  notify:
  - firewalld_restart

