---
- include_tasks: hostname.yml
- include_tasks: packages.yml
#- include_tasks: check_ambari.yml
- include_tasks: firewall-config.yml
- include_tasks: ambari-repo.yml
- include_tasks: ambari-install.yml
- include_tasks: ambari-setup.yml
#  when: ambari_file.stat.exists
