---
- include_tasks: hostname.yml
- include_tasks: packages.yml
- include_tasks: firewall-config.yml
- include_tasks: ambari-check.yml
- include_tasks: ambari-execute-install.yml
  when: ansible_facts.services['ambari-server.service'] is not defined
- include_tasks: blueprint-cluster.yml